"""Shipped baseline seed.

A seed is a pre-built baseline (snapshots + feed seen-set + HTTP validators)
generated by ``scripts/build_seed.py`` and bundled as ``seed.sql.gz``. On a
fresh DB it gives users a starting point so the first scheduled run diffs
against the seeded baseline instead of crawling every page from scratch.

The bundled artifact is optional: when it is absent (e.g. before a release has
generated it), import is a graceful no-op and the first run falls back to the
fetch-free baseline the sitemap detector establishes on its own.
"""

from __future__ import annotations

import gzip
import logging
from importlib.resources import files

log = logging.getLogger("android_watcher.seed")

_SEED_FILE = "seed.sql.gz"


def bundled_seed_sql() -> str | None:
	"""Return the decompressed bundled seed SQL, or None if no seed is shipped."""
	resource = files(__name__).joinpath(_SEED_FILE)
	if not resource.is_file():
		return None
	return gzip.decompress(resource.read_bytes()).decode()


def apply_seed_if_empty(store) -> str | None:
	"""Import the bundled seed into a fresh (snapshot-less) DB.

	Returns the seed date when a seed was applied, else None. Safe to call on
	every run: it short-circuits once any snapshot exists, and the seed's
	``INSERT OR IGNORE`` statements never overwrite user data.
	"""
	if store.snapshot_count() > 0:
		return None
	sql = bundled_seed_sql()
	if sql is None:
		return None
	store.import_seed_sql(sql)
	return store.seed_date()
