class AndroidWatcher < Formula
  include Language::Python::Virtualenv

  desc "Self-hosted CLI that watches Google's Android sites and delivers AI-triaged digests"
  homepage "https://github.com/krayong/android-watcher"
  # url + sha256 point at the PyPI sdist for the released version. The release
  # workflow rewrites both on every version bump, then regenerates the `resource`
  # blocks below with `brew update-python-resources`. Do not hand-edit.
  url "https://files.pythonhosted.org/packages/source/a/android-watcher/android_watcher-0.0.0.tar.gz"
  sha256 "0000000000000000000000000000000000000000000000000000000000000000"
  license "MIT"

  depends_on "python@3.11"

  # Dependency `resource` blocks are generated by the release workflow:
  #   brew update-python-resources Formula/android-watcher.rb
  # One hash-pinned block per transitive dependency lands here. Never fabricate
  # a url or sha256 by hand.

  def install
    virtualenv_install_with_resources
  end

  test do
    assert_match "android-watcher", shell_output("#{bin}/android-watcher --help")
  end
end
