#!/usr/bin/env python3
"""Regenerate the Homebrew formula for a released version.

Deterministic and self-contained: resolves the dependency closure with
``uv pip compile`` and pulls each sdist's url + sha256 from PyPI's JSON API,
then writes ``Formula/android-watcher.rb`` from a template. It uses no Homebrew
tooling, so it is immune to the three things that make ``brew
update-python-resources`` fail in CI on a fresh release: the tap requirement,
tap-trust, and Homebrew's PyPI reproducibility cutoff (which excludes a
same-day upload).

Usage:
    python3 scripts/update_formula.py <version>
"""

from __future__ import annotations

import json
import subprocess
import sys
import time
import tomllib
import urllib.error
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PYPROJECT = ROOT / "pyproject.toml"
FORMULA = ROOT / "Formula" / "android-watcher.rb"
PROJECT_NAME = "android-watcher"

FORMULA_TEMPLATE = """class AndroidWatcher < Formula
  include Language::Python::Virtualenv

  desc "Self-hosted CLI that watches Google's Android sites and delivers AI-triaged digests"
  homepage "https://github.com/krayong/android-watcher"
  # url + sha256 and the resource blocks below are generated by
  # scripts/update_formula.py on every release. Do not hand-edit.
  url "{url}"
  sha256 "{sha256}"
  license "MIT"

  depends_on "python@3.11"

{resources}

  def install
    virtualenv_install_with_resources
  end

  test do
    assert_match "android-watcher", shell_output("#{{bin}}/android-watcher --help")
  end
end
"""


def _project_dependencies() -> list[str]:
	data = tomllib.loads(PYPROJECT.read_text())
	return list(data["project"]["dependencies"])


def _resolve_closure(dependencies: list[str]) -> list[tuple[str, str]]:
	"""Return the full transitive closure as sorted (name, version) pairs."""
	proc = subprocess.run(
		["uv", "pip", "compile", "--python-version", "3.11", "--no-header", "--no-annotate", "-"],
		input="\n".join(dependencies),
		capture_output=True,
		text=True,
		check=True,
	)
	pins: list[tuple[str, str]] = []
	for line in proc.stdout.splitlines():
		line = line.split("#", 1)[0].strip()
		if not line or "==" not in line:
			continue
		name, version = line.split("==", 1)
		name = name.strip()
		if name.lower() == PROJECT_NAME:  # never list ourselves as a resource
			continue
		pins.append((name, version.strip()))
	return sorted(pins)


def _pypi_sdist(name: str, version: str, *, retries: int = 1) -> tuple[str, str]:
	"""Return (url, sha256) for the sdist of name==version, retrying on lag."""
	url = f"https://pypi.org/pypi/{name}/{version}/json"
	last: Exception | None = None
	for attempt in range(retries):
		try:
			data = json.load(urllib.request.urlopen(url))
		except urllib.error.HTTPError as exc:  # 404 while PyPI indexes a fresh upload
			last = exc
			time.sleep(min(10, 2 * (attempt + 1)))
			continue
		for u in data["urls"]:
			if u["packagetype"] == "sdist":
				return u["url"], u["digests"]["sha256"]
		raise SystemExit(f"no sdist on PyPI for {name}=={version}")
	raise SystemExit(f"could not fetch {name}=={version} from PyPI: {last}")


def _resource_block(name: str, url: str, sha256: str) -> str:
	return f'  resource "{name}" do\n    url "{url}"\n    sha256 "{sha256}"\n  end'


def main(argv: list[str]) -> int:
	if len(argv) != 2:
		print("usage: update_formula.py <version>", file=sys.stderr)
		return 2
	version = argv[1]

	main_url, main_sha = _pypi_sdist(PROJECT_NAME, version, retries=30)
	closure = _resolve_closure(_project_dependencies())
	blocks = [_resource_block(name, *_pypi_sdist(name, ver)) for name, ver in closure]

	formula = FORMULA_TEMPLATE.format(
		url=main_url,
		sha256=main_sha,
		resources="\n\n".join(blocks),
	)
	FORMULA.write_text(formula)
	print(f"wrote {FORMULA.relative_to(ROOT)} for v{version} with {len(blocks)} resources")
	return 0


if __name__ == "__main__":
	raise SystemExit(main(sys.argv))
